{"body": "\nI was having problems with HB and I decided to update the plugin by using the HB update component and I returns an error:\n\n\u00a0\n\n[<img class=\"align-full\" src=\"http://api.ning.com:80/files/HbsRLQ*GNXYrmdiJfR35rRWNIyULwRHgsrzzKZJLuUXGcTDijOBOhNYkWX0dv7zdI2RJOYNlLZuIrTclQYtAmDpkHZHM2cLt/Canvasat104842.png?width=750\" width=\"750\"/>](http://api.ning.com:80/files/HbsRLQ*GNXYrmdiJfR35rRWNIyULwRHgsrzzKZJLuUXGcTDijOBOhNYkWX0dv7zdI2RJOYNlLZuIrTclQYtAmDpkHZHM2cLt/Canvasat104842.png)\n", "attachments": [], "created_by_name": "Claudio", "created_at": "October 15, 2014 at 8:49am", "created_by": "Claudio", "topic": "Fail to Update HB and LB", "replies": [{"body": "\nI can reproduce this on my system. I will take a look soon. Thanks for reporting. - Mostapha\n", "attachments": [], "created_by_name": "Mostapha Sadeghipour Roudsari", "created_at": "October 15, 2014 at 12:29pm", "created_by": "MostaphaSadeghipour", "replies": [{"body": "\nHi again Claudio, I spent some time now and tested the process. Looks like github is blocking automated requests for downloading the files. There are workarounds for this which I will apply once I get a chance... Meanwhile you need to update them manually! :|\n\n[https://github.com/mostaphaRoudsari/Honeybee/issues/194](https://github.com/mostaphaRoudsari/Honeybee/issues/194)\n\n\n", "attachments": [], "created_by_name": "Mostapha Sadeghipour Roudsari", "created_at": "October 15, 2014 at 11:26pm", "created_by": "MostaphaSadeghipour", "replies": []}, {"body": "\nIf you clone the repo on your local drive you can provide the address to userobjects, similar to this image:\n\n[<img class=\"align-center\" src=\"http://api.ning.com:80/files/6q4t4dNL56mlUCn4XxdwqX03Iws0vsub4DM32Jf4VEn3ZNoBscjsNYl6hEcrT*8AJnn3NzhNA3QWfR9qV0gGur8*9dt-HY3y/update_Ladybug_Honeybee.png\" width=\"652\"/>](http://api.ning.com:80/files/6q4t4dNL56mlUCn4XxdwqX03Iws0vsub4DM32Jf4VEn3ZNoBscjsNYl6hEcrT*8AJnn3NzhNA3QWfR9qV0gGur8*9dt-HY3y/update_Ladybug_Honeybee.png)\n", "attachments": [], "created_by_name": "Mostapha Sadeghipour Roudsari", "created_at": "October 15, 2014 at 11:30pm", "created_by": "MostaphaSadeghipour", "replies": []}, {"body": "\nJust to report: Adding the panel indeed doesn't report an error, but ... the path you give in it remains empty. Nothing is downloaded (in my end at least).\n\n-A.\n", "attachments": [], "created_by_name": "Abraham Yezioro", "created_at": "November 4, 2014 at 9:25am", "created_by": "AbrahamYezioro", "replies": []}, {"body": "\nHi Abraham, you need to download the files manually and then let the component know where to find them. This is the address to the files on my system and you need to modify it based on the location of userObjects on your system. Best, -Mostapha\n", "attachments": [], "created_by_name": "Mostapha Sadeghipour Roudsari", "created_at": "November 5, 2014 at 11:30pm", "created_by": "MostaphaSadeghipour", "replies": []}, {"body": "\nHi Abraham, FYI I just \u00a0committed a new version that should fix this issue.\n", "attachments": [], "created_by_name": "Mostapha Sadeghipour Roudsari", "created_at": "January 20, 2015 at 8:30pm", "created_by": "MostaphaSadeghipour", "replies": []}, {"body": "\nHi Mostapha,\n\nThanks but ...\n\nI suppose the other discussions relate to this one also. I'm using the update_ssl.gh file you attached in other thread.\n\nSo i downloaded the ssl.py and copied it to the directory mentioned in the LB_Updater. But still don't update the file. Still having the same message.\n\nI closed Rhino and reopened it but still not working.\n\n-A.\n", "attachments": [], "created_by_name": "Abraham Yezioro", "created_at": "January 20, 2015 at 10:56pm", "created_by": "AbrahamYezioro", "replies": []}, {"body": "\nHi Abraham,\n\nThanks. Can you tell me what is the folder? Hopefully I didn't upload the wrong file to box. Can you try the attached file?\n\nI need to go to bed right now but I will check again tomorrow after work so please take your time!\n\nMostapha\n", "attachments": [{"link": "http://www.grasshopper3d.com/group/ladybug/forum/attachment/download?id=2985220%3AUploadedFile%3A1208205", "name": "ssl.py"}], "created_by_name": "Mostapha Sadeghipour Roudsari", "created_at": "January 20, 2015 at 11:11pm", "created_by": "MostaphaSadeghipour", "replies": []}, {"body": "\nNo problem,\n\nThe message says:\n\nDownloading the source code...IOError(&lt;System.IO.IOException object at 0x000000000000002B [System.IO.IOException: Authentication failed because the remote party has closed the transport stream....]&gt;,)Download ssl.py from the link below and copy the file to\n\nc:\\Program Files\\Rhinoceros 5 (64-bit)\\Plug-ins\\IronPython\\Lib and try again![https://app.box.com/s/jvsj1ic60vnficptlktt0jpfutcktemqI](https://app.box.com/s/jvsj1ic60vnficptlktt0jpfutcktemqI) also unblocked the file.\n\nThanks,\n\n-A.\n", "attachments": [], "created_by_name": "Abraham Yezioro", "created_at": "January 21, 2015 at 1:07am", "created_by": "AbrahamYezioro", "replies": []}, {"body": "\nThanks. Can you please try this file. It will download two files to c:\\ladybug on your system and if it works I can get update components fixed later: \u00a0[https://www.dropbox.com/s/0bitdduywpgvycu/downloading_issues.gh?dl=0](https://www.dropbox.com/s/0bitdduywpgvycu/downloading_issues.gh?dl=0)\n", "attachments": [], "created_by_name": "Mostapha Sadeghipour Roudsari", "created_at": "January 21, 2015 at 10:39am", "created_by": "MostaphaSadeghipour", "replies": []}, {"body": "\nIn My case the ssl.py did not work neither. The 2 files versions.tx. and a master.zip where downloaded to c:\\ladybug.\n\nThe report gives this message\n\n0.345413208008 1421863665.39\n\n\n\nThank you for your help\n", "attachments": [], "created_by_name": "Claudio", "created_at": "January 21, 2015 at 11:10am", "created_by": "Claudio", "replies": []}]}, {"body": "", "attachments": [], "created_by_name": "Abraham Yezioro", "created_at": "January 21, 2015 at 10:56am", "created_by": "AbrahamYezioro", "replies": []}]}