{"body": "\nSo, while trying to run one of my first energy simulations with Grasshopper + Honeybee, I got the following output:\n\n**\"1. Solution exception:A chave fornecida n\u00e3o estava presente no dicion\u00e1rio.\"**\n\nDon\u00b4t know why it came out in portuguese, my native language, but I guess the translation for that would be **\u00a0\"1. Solution exception: The given key was not present in the dictionary\".** Still, I have no idea what that means. Would anyone happen to know what might be the problem and how to fix it?\u00a0\n\n\n\nThank you!!\u00a0\n", "attachments": [{"link": "http://www.grasshopper3d.com/group/ladybug/forum/attachment/download?id=2985220%3AUploadedFile%3A1564308", "name": "Eplus_simulation_error.jpg"}, {"link": "http://www.grasshopper3d.com/group/ladybug/forum/attachment/download?id=2985220%3AUploadedFile%3A1564309", "name": "Experimento.gh"}], "created_by_name": "Ana Carolina Moura", "created_at": "July 11, 2016 at 9:54pm", "created_by": "AnaCarolinaMoura", "topic": "Error when trying to run E+ simulation: \" Solution exception:A chave fornecida n\u00e3o estava presente no dicion\u00e1rio.\"", "replies": [{"body": "\nAna,\n\nYou did not internalize your geometry in your GH script and so I cannot find \u00a0the error. \u00a0Also, your components are older than the version that is currently on the github and I would update your file before re-posting.\n\n-Chris\n", "attachments": [], "created_by_name": "Chris Mackey", "created_at": "July 11, 2016 at 10:23pm", "created_by": "ChrisMackey", "replies": []}], "id": "1564710"}