{"body": "\nMehrnoosha and Michal, Unfortunately I can't reproduce this error. Can you please test the attached file and let me know if it works fine?\n\nAs If it still gives you the error can you please open the editor and click on test and tell me what the error is? As far as I can see the error happens in line 35.\n", "attachments": [{"link": "http://www.grasshopper3d.com/group/ladybug/forum/attachment/download?id=2985220%3AUploadedFile%3A1012171", "name": "testGHPython.0.6.0.3.gh"}], "created_by_name": "Mostapha Sadeghipour Roudsari", "created_at": "February 19, 2014 at 8:33pm", "created_by": "MostaphaSadeghipour", "parent_id": "reply_2985220_Comment_1012321", "id": "reply_2985220_Comment_1012170"}